on: [push, pull_request]
name: Test
jobs:
  test:
    name: Test
    runs-on: macOS-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Build and test
        run: |
          gem update --system
          gem install bundler
          bundle install
          bundle exec fastlane test
